"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { rankModels, filterModels, escapeHTML } = require("../docs/leaderboard/leaderboard-core.js");
const data = JSON.parse(fs.readFileSync(path.join(__dirname, "../docs/leaderboard/results.json"), "utf8"));
const snapshot = JSON.stringify(data);
const all = rankModels(data.models, "gacc_all");
assert.deepEqual(all.map(model => model.id), ["gemini-3.8-flash", "qwen3.5-27b", "gpt-6-astra", "qwen3.5-9b", "qwen3.5-4b", "internvl3.5-8b"]);
assert.deepEqual(all.map(model => model.rank), [1, 2, 3, 4, 5, 6]);
assert.deepEqual(rankModels(data.models, "gacc_all", "qWeN").map(model => model.rank), [2, 4, 5]);
assert.equal(rankModels(data.models, "jacc")[0].id, "gpt-6-astra");
assert.equal(rankModels(data.models, "gacc_all", "", "api").length, 2);
assert.equal(filterModels(data.models, "", "open_weights").length, 4);
assert.equal(rankModels(data.models, "jacc", "no matching model").length, 0);
assert.throws(() => rankModels(data.models, "paired_delta"), /Unknown ranking metric/);
assert.deepEqual(rankModels([{name:"A",gacc_all:90},{name:"B",gacc_all:90},{name:"C",gacc_all:80}]).map(model => model.rank), [1, 1, 3]);
assert.equal(escapeHTML('<img src="x">&'), "&lt;img src=&quot;x&quot;&gt;&amp;");
assert.equal(data.models.find(model => model.id === "gpt-6-astra").paired.delta_pp, 1.32);
assert.equal(data.models.find(model => model.id === "gemini-3.8-flash").paired.delta_pp, 2.20);
assert.equal(data.populations.all.probes, 3341);
assert.equal(JSON.stringify(data), snapshot, "Sorting and filtering must not mutate the source results");
console.log("Leaderboard: rankings, shared ranks, filters, source scopes, rounding and escaping passed.");
